export enum GameStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  ROUND_IN_PROGRESS = 'ROUND_IN_PROGRESS',
  ROUND_ENDED = 'ROUND_ENDED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
